version: '3'
services:
  grafana:
    image: grafana/grafana
    env_file: docker.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:11.1-alpine
    env_file: docker.env
    ports:
      - "5432:5432"
