{
 "title": "screeps",
 "time": { "from": "2019-02-28T06:42:35.114Z", "to": "2019-02-28T10:55:45.190Z" },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  (\n  NOW() - (\n    (SELECT MAX(time) FROM screeps_data) - time\n    )\n    * 3\n    * interval '1 seconds'\n  ) AS \"time\",\n  cpu,\n  20 as \"limit\"\nFROM screeps_data\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Population",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  (\n  NOW() - (\n    (SELECT MAX(time) FROM screeps_data) - time\n    )\n    * 3\n    * interval '1 seconds'\n  ) AS \"time\",\n  population\nFROM screeps_data\nORDER BY 1"
    }
   ]
  },
  {
   "title": "GCL Delta",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  (\n  NOW() - (\n    (SELECT MAX(time) FROM screeps_data) - a.time\n    )\n    * 3\n    * interval '1 seconds'\n  ) AS \"time\",\n  a.gcl_progress - b.gcl_progress as \"progress\"\nFROM screeps_data a\nLEFT JOIN screeps_data b\nON a.time = b.time + 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "GCL Progress",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  (\n  NOW() - (\n    (SELECT MAX(time) FROM screeps_data) - time\n    )\n    * 3\n    * interval '1 seconds'\n  ) AS \"time\",\n  gcl_progress / gcl_total * 100 as value\nFROM screeps_data\nORDER BY 1"
    }
   ]
  }
 ]
}